name: Build
on: 
    push: 
        branches: 
            - main
    pull_request: 
        branches: 
            - main

jobs: 
    gradle-build: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v5

            - uses: actions/setup-java@v4
              with: 
                  distribution: 'zulu'
                  java-version: '23'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Gradle Build
              run: ./gradlew build
