name: Build
on: push

jobs: 
    gradle: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with: 
                  distribution: 'zulu'
                  java-version: '17'

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2

            - name: Gradle Build
              run: ./gradlew build